theme: jekyll-theme-cayman
title: JuliaNLSolvers
description: Julia packages for solving systems of nonlinear equations and minimizing nonlinear functions 

github:
  repository_url: https://github.com/JuliaNLSolvers
